-- ─────────────────────────────────────────────────────
-- 014: NOTIFICATIONS TABLE
-- Stores in-app notifications for Sales Managers.
-- Generated by: sessionController (score events, completion, attempt limits),
--               assignmentController (new assignment),
--               notificationController (deadline scanner)
-- ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id UUID NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
  manager_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Notification classification
  type TEXT NOT NULL CHECK (type IN (
    'assignment_overdue',
    'score_critical',       -- score < 50
    'attempt_limit',        -- attempt limit reached
    'assignment_completed',
    'score_low',            -- score 50–64
    'no_activity',          -- no session in 3+ days
    'training_started',     -- rep started (Pending → In Progress)
    'score_improved',       -- score improved by 15+ pts
    'deadline_approaching', -- due within 48h
    'assignment_created',   -- manager confirmation
    'score_high',           -- score >= 85
    'scenario_updated'      -- scenario library change
  )),
  priority TEXT NOT NULL CHECK (priority IN ('critical', 'high', 'medium', 'low')) DEFAULT 'medium',

  -- Display content
  title TEXT NOT NULL,
  body TEXT NOT NULL,

  -- Contextual data for deep-linking / detail rendering
  metadata JSONB DEFAULT '{}'::jsonb,
  -- expected keys: repName, repId, scenarioTitle, assignmentId, sessionId, score, prevScore

  read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_manager_id ON notifications(manager_id);
CREATE INDEX IF NOT EXISTS idx_notifications_org_id ON notifications(org_id);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications(type);

-- RLS: service_role can do everything
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_all_notifications" ON notifications
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Auto update_at trigger (not needed since we only INSERT + UPDATE read)
